# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af3c9a17277e5aa7f3288b0647fdb27a0d3e235006a02623c8088576fd3a7b18124e48629a89de463f08b3e81747a66281ea3a5c10a88af3bf36a97078c2c1cf

test:
  secret_key_base: 9e8414951e9c26aa414a67ebb61c003da52ccd24012f001b5d19e38d1cf4b160dc93539c69951de7d529ed79a02575d12d1e99ac2e73a3dae1296af4fff3e293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
